version: "3.8"
services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    networks: -todoapp-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
  todoapp-network:
    external: true
